[advanced-alt-tab-window-switcher]
super-key-mode=1
switcher-popup-monitor=2
switcher-popup-position=2
switcher-popup-preview-selected=1
win-switcher-popup-titles=2
win-switcher-popup-ws-indexes=false

[arch-update]
always-visible=false
boot-wait=20
check-interval=600
howmuch=0
show-count=true
use-buildin-icons=false

[burn-my-windows]
close-preview-effect=''
destroy-dialogs=true
energize-a-open-effect=false
energize-b-open-effect=false
fire-animation-time=880
fire-close-effect=false
flame-scale=0.8
hexagon-animation-time=500
hexagon-open-effect=true
hexagon-scale=2.5
matrix-animation-time=1142
matrix-close-effect=false
matrix-scale=15
open-preview-effect=''
snap-close-effect=false
trex-close-effect=false
tv-close-effect=true
tv-open-effect=true

[com/github/hermes83/compiz-windows-effect]
friction=3.5
mass=75.0
maximize-effect=true
resize-effect=false
speedup-factor-divider=14.0
spring-k=8.5
x-tiles=4.0
y-tiles=4.0

[dash-to-dock]
apply-custom-theme=true
background-opacity=0.8
dash-max-icon-size=58
dock-position='LEFT'
height-fraction=0.76
preferred-monitor=0
preview-size-scale=0.8

[desktop-cube]
appgrid-transition-time=0
enable-desktop-dragging=false
enable-desktop-edge-switch=false
enable-overview-edge-switch=false
enable-panel-dragging=false
inactive-workpace-opacity=167
overview-transition-time=0
per-monitor-perspective=true
window-parallax=0.3
workspace-transition-time=0

[user-theme]
name='Sweet-Dark'

[vitals]
position-in-panel=2

[window-list]
grouping-mode='auto'
